# Generated by Django 3.2.4 on 2021-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0003_allocationstate_pid"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstate",
            name="message",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="allocationstate",
            name="runtime",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="allocationstate",
            name="status",
            field=models.TextField(default="Requested"),
        ),
        migrations.AddField(
            model_name="allocationstate",
            name="type",
            field=models.TextField(null=True),
        ),
    ]
