# Generated by Django 3.2.9 on 2021-11-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0004_auto_20211123_1009"),
    ]

    operations = [
        migrations.RenameField(
            model_name="allocationstate",
            old_name="status",
            new_name="title",
        ),
    ]
