# Generated by Django 3.2.9 on 2021-11-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0005_rename_status_allocationstate_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationstate",
            name="title",
            field=models.TextField(default="Allocation Requested"),
        ),
    ]
