# Generated by Django 3.2.9 on 2021-11-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0006_alter_allocationstate_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstate",
            name="timeout",
            field=models.IntegerField(default=3600),
            preserve_default=False,
        ),
    ]
