image: node:14

pipelines:
  branches:
    development:
      - step:
          name: 'Push changes back to github'
          script:
            - git config user.name "Mike Pham"
            - git config user.email "31090859+mike-fam@users.noreply.github.com"
            - git remote add github git@github.com:mike-fam/allocator_v2.git
            - git push github development:main
      - step:
          name: 'Deployment to Production'
          deployment: production
          trigger: 'manual'
          script:
            - chmod +x ./scripts/production/deploy.sh
            - ./scripts/production/deploy.sh
