# Generated by Django 3.2.4 on 2021-11-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allocator", "0002_alter_allocationstate_data_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstate",
            name="pid",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
